# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:34
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),

            ],
        ),
    ]
